apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
  annotations:
    "vault.hashicorp.com/agent-inject": "true"
    "vault.hashicorp.com/agent-inject-secret-mydbpassword": "secretos/basedatos/password"
    "vault.hashicorp.com/role": "webapp"
    "vault.hashicorp.com/log-level": "debug"
spec:
  containers:
    - name: demo
      image: nginx